//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.udistrital.mcic.informatica.iot.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class noise
    {
        public int idNoise { get; set; }
        public System.DateTime dateNoise { get; set; }
        public double levelNoise { get; set; }
    }
}
